name: Create Pack
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6.4

    - name: Create Pack
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH }}
        script: |
          [ ! -d "./packs/Classic-Faithful-32x-Prog-Art/${{ steps.branch-name.outputs.current_branch }}" ] && exit 1
          cd "./packs/Classic-Faithful-32x-Prog-Art/${{ steps.branch-name.outputs.current_branch }}"
          git pull
          zip -r "Classic Faithful 32x Programmer Art - ${{ steps.branch-name.outputs.current_branch }}.zip" . -x "*.git*" -x "*.github*" -x ".gitignore"
          mv "Classic Faithful 32x Programmer Art - ${{ steps.branch-name.outputs.current_branch }}.zip" "/var/www/html/database.faithfulpack.net/packs/Classic-32x-Java/Programmer Art"